// Generated by CoffeeScript 1.6.3
(function() {
  var Gitlab, credentials, gitlab;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  Gitlab = require('gitlab').ApiV3;

  credentials = require('./credentials');

  gitlab = new Gitlab({
    url: credentials.url,
    token: credentials.token,
    verbose: true
  });

  params = {
    user_id: parseInt(process.argv[2]),
    name: process.argv[3]
  };

  gitlab.projects.createu(params, function(project) {
    if(project.message)
      console.log(project.message);
    else{
      console.log(project);
//       var exec = require('child_process').exec;
//       //TODO (Nelian): incorporate get user by id
//       exec('./script.sh ' + project.name,
//       function (error, stdout, stderr) {
//       console.log('stdout: ' + stdout);
//       console.log('stderr: ' + stderr);
    
//       if (error !== null) {
//         console.log('exec error: ' + error);
//       }
// });
    }
  });

  

}).call(this);
